# Quality Assurance Configuration
# Professional QA standards for Qt5 Industrial HMI Application

# Code Coverage Targets
coverage:
  target: 85
  critical_target: 95
  exclude_patterns:
    - "*/tests/*"
    - "*/build-*/*" 
    - "*/mxe-lite/*"
    - "*/deps/*"
    - "*/external/*"

# Static Analysis Configuration
static_analysis:
  cppcheck:
    enabled: true
    rules:
      - "style"
      - "performance"
      - "portability"
      - "warning"
      - "error"
    exclude_paths:
      - "deps/"
      - "tests/mocks/"
    
  clang_tidy:
    enabled: true
    checks:
      - "readability-*"
      - "performance-*"
      - "modernize-*"
      - "bugprone-*"
      - "cppcoreguidelines-*"
    exclude_checks:
      - "modernize-use-trailing-return-type"
      - "readability-magic-numbers"

# Test Configuration
testing:
  unit_tests:
    timeout: 30
    parallel: true
    coverage_required: true
    
  integration_tests:
    timeout: 120
    retry_count: 2
    coverage_required: false
    
  performance_tests:
    timeout: 180
    memory_limit: "512MB"
    cpu_limit: "200%"
    
# Performance Benchmarks
performance:
  startup_time:
    target: "< 2000ms"
    critical: "< 5000ms"
    
  memory_usage:
    target: "< 50MB"
    critical: "< 100MB"
    
  udp_response_time:
    target: "< 100ms"
    critical: "< 500ms"
    
  gui_responsiveness:
    target: "60fps"
    critical: "30fps"

# Security Requirements
security:
  vulnerability_scan: true
  dependency_check: true
  static_security_analysis: true
  
  allowed_vulnerabilities:
    low: 10
    medium: 5
    high: 0
    critical: 0

# Build Quality Gates
quality_gates:
  - name: "Unit Tests Pass"
    required: true
    blocking: true
    
  - name: "Integration Tests Pass"
    required: true
    blocking: true
    
  - name: "Code Coverage >= 85%"
    required: true
    blocking: true
    
  - name: "No High/Critical Security Issues"
    required: true
    blocking: true
    
  - name: "Performance Benchmarks Met"
    required: true
    blocking: false
    
  - name: "Static Analysis Clean"
    required: true
    blocking: false

# Platform Requirements
platforms:
  linux:
    - "Ubuntu 20.04 LTS"
    - "Ubuntu 22.04 LTS"
    - "CentOS 8"
    
  windows:
    - "Windows 10 x64"
    - "Windows 11 x64"
    
# Documentation Requirements
documentation:
  api_coverage: 90
  code_comments: 75
  user_documentation: true
  
# Deployment Validation
deployment:
  smoke_tests: true
  integration_tests: true
  performance_validation: true
  security_validation: true