// This file is autogenerated. Changes will be overwritten.
#include "VNU7RW3YIC/moc_controllermanager.cpp"
#include "VNU7RW3YIC/moc_industrialcontroller.cpp"
#include "VNU7RW3YIC/moc_udpservice.cpp"
