// This file is autogenerated. Changes will be overwritten.
#include "543F6OVNPU/moc_mockcontrollermanager.cpp"
#include "543F6OVNPU/moc_mockindustrialcontroller.cpp"
#include "543F6OVNPU/moc_mockudpservice.cpp"
